# One line per downstream pipeline: <watched-path>:<buildkite-pipeline-slug>
# services/service-b:service-b-pipeline below means we are watching the services/service-b folder and will trigger a Buildkite pipeline named service-b-pipeline when there are changes to the path.
services/service-b:service-b-pipeline
services/service-a:service-a-pipeline