steps:
  - label: ":python: Lint"
    command: "echo 'pretend: flake8 services/service-a'"

  - wait

  - label: ":python: Test"
    command: "echo 'pretend: pytest services/service-a'"

  - label: ":docker: Build image"
    command: "echo 'pretend: docker build -t service-a services/service-a'"
    branches: "main"
